### ISSUE TITLE
The markup grammar is strange in 'Authentication using LDAP' page

### ISSUE THREAD

**Issue by epicarts** [fosslight/fosslight-guide#16]
The markup grammar seems to be applied strangely in [Authentication using LDAP page](https://fosslight.org/fosslight-guide-en/started/2_try/8_configuration.html#authentication-using-ldap).

Guide page written `ldap://:.`.  
However, look at the code, it's `ldap://<AD_SERVER_IP>:<LDAP_PORT>`.

It looks like it needs to be fixed. both en guide and ko guide.

**Comment by soimkim** [comment]
@epicarts , I am waiting for your contribution.
